import { InMemoryDbService } from 'angular-in-memory-web-api';

export class MockDataService implements InMemoryDbService {
  createDb() {
    let brands = [
      {id: 11, name: '12 Survivors'},
      {id: 12, name: '5.11'},
      {id: 13, name: '5.11 Tctical Series'},
      {id: 14, name: 'AccuSharp'},
      {id: 15, name: 'Adam Unlimited'},
      {id: 16, name: 'Adventure Medical Kits'},
      {id: 17, name: 'Al Mar'},
      {id: 18, name: 'Alar-DISC'},
      {id: 19, name: 'Alpen'},
      {id: 20, name: 'Alps Cedar Ridge'}
    ];

    let categories = [
      {id: 11, name: 'Knives - Fixed Blades'},
      {id: 12, name: 'Knives - Folders'},
      {id: 13, name: 'Knives - Accessories'},
      {id: 14, name: 'Knives - Fantasy'},
      {id: 15, name: 'Knives - Throwing'},
      {id: 16, name: 'Knives - Handmade'},
    ];

    let prices = [
      {id: 1, name: '$1.00 - $9.99'},
      {id: 2, name: '$10.00 - $24.99'},
      {id: 3, name: '$25.00 - $49.99'},
      {id: 4, name: '$50.00 - $74.99'},
      {id: 5, name: '$75.00 - $99.99'},
      {id: 6, name: '$100.00 and over'},
    ];

    // let products = [
    //   { 
    //     productId: 1, 
    //     manufacturerName: 'Spyderco',
    //     categoryName: 'Knives - Folders',
    //     productName: 'Byrd Finch 2, Black G10 Handle, Satin Plain',description: 'The Finch2 folder from byrd makes an excellent pocket knife. It is small in size, yet strong in hand. The blade is flat ground 8Cr13MoV steel with a thumb hole for easy one-hand opening. Textured black G-10 handle with steel liners, screw construction, and back lock. The Finch2 has a lanyard hole for pocket carry or attachment to a keychain',
    //     supplierName: 'Moteng', 
    //     features: 'The Finch2 folder from byrd makes an excellent pocket knife. It is small in size, yet strong in hand. The blade is flat ground 8Cr13MoV steel with a thumb hole for easy one-hand opening. Textured black G-10 handle with steel liners, screw construction, and back lock. The Finch2 has a lanyard hole for pocket carry or attachment to a keychain.',
    //     sku: 'BY11GP2',
    //     imageUrl: 'http://productimages.moteng.com/BY11GP2.jpg',
    //     price: 20.00
    //   },
    //   { 
    //     productId: 2, 
    //     manufacturerName: 'Spyderco',
    //     categoryName: 'Knives - Folders',
    //     productName: 'Byrd Finch 2, Black G10 Handle, Satin Plain',description: 'The Finch2 folder from byrd makes an excellent pocket knife. It is small in size, yet strong in hand. The blade is flat ground 8Cr13MoV steel with a thumb hole for easy one-hand opening. Textured black G-10 handle with steel liners, screw construction, and back lock. The Finch2 has a lanyard hole for pocket carry or attachment to a keychain',
    //     supplierName: 'Moteng', 
    //     features: 'The Finch2 folder from byrd makes an excellent pocket knife. It is small in size, yet strong in hand. The blade is flat ground 8Cr13MoV steel with a thumb hole for easy one-hand opening. Textured black G-10 handle with steel liners, screw construction, and back lock. The Finch2 has a lanyard hole for pocket carry or attachment to a keychain.',
    //     sku: 'BY11GP2',
    //     imageUrl: 'http://productimages.moteng.com/BY11GP2.jpg',
    //     price: 20.00
    //   }
    // ];

    let slideshowImages = [
      {id: 1, name: '', path:'/Images//Slideshow/slide-show-image-1.jpg'},
      {id: 2, name: '', path:'/Images/Slideshow/slide-show-image-2.jpg'},
      {id: 3, name: '', path:'/Images/Slideshow/slide-show-image-3.jpg'},
      {id: 4, name: '', path:'/Images/Slideshow/slide-show-image-4.jpg'},
      {id: 5, name: '', path:'/Images/Slideshow/slide-show-image-5.jpg'},
      {id: 6, name: '', path:'/Images/Slideshow/slide-show-image-6.jpg'},
      {id: 7, name: '', path:'/Images/Slideshow/slide-show-image-7.jpg'},
      {id: 8, name: '', path:'/Images/Slideshow/slide-show-image-8.jpg'},
      {id: 9, name: '', path:'/Images/Slideshow/slide-show-image-9.png'},
      {id: 10, name: '', path:'/Images/Slideshow/slide-show-image-10.jpg'},
    ];
    
    let products = [
      	{
			"Id": 374972,
			"SKU": "4008304",
			"Description": "This â€œfree standingâ€ backpack allows for hands free transportation to and from the range. The â€œHandgunner Backpackâ€ was designed to allow the avid handgun shooter a way to transport their handguns, 12 extra magazines, ammo, shooting glasses, ear protection, targets, stapler, tape, binos, shooting mats, cleaning supplies all in a compact backpack. By utilizing the visual ID storage system G.P.S. has designed separate pockets that store your most frequently used items for added protection and easy retrieval. The most unique feature is the inside storage cradle that slides in and out of the lower compartment. This foam cradle was designed to hold 4 medium to small size handguns in a vertical format. This vertical format allows for ease of use at the range and added protection from 360 degrees. This Cradle is made of high density foam and is cut with a CNC machine to cradle each pistol by its trigger guard. Just slide out the cradle at the range and keep all 4 pistols organized. After shooting, remove the cradle with the handguns inside for cleaning and then for storage in your gun safe. No need to open and close pistol cases or rugs each time you intend to use. The â€œHandgunnerâ€ backpack also features a waterproof pull out cover to help keep the contents dry in case of a sudden downpour.",
			"Name": "G.P.S. Handgunner Backpack Tan",
			"ItemNumber": "GPS-1711BPT",
			"RetailPrice": 124.25,
			"ImageUrl": "http://www.motengna.com/core/media/media.nl?id=2935413&c=902676&h=7b517345f374c68c8d41",
			"SupplierId": 1,
			"SupplierName": "Moteng",
			"ManufacturerId": 8760,
			"ManufacturerName": "G Outdoors",
			"CategoryId": 13444,
			"CategoryName": "Shooting : Accessories"
		},
		{
			"Id": 374973,
			"SKU": "4008319",
			"Description": "The original model of the Urban Trapper from Brad Zinker has quickly developed into one of the most popular gentleman's knives from BÃ¶ker Plus. The extremely low-profile and slender design in combination with refined materials such as VG-10, titanium and an IKBS hinge result in an incomparable pocketknife for demanding tastes. This version offers additional scales on the titanium handle, which provide a slightly fuller grip feel in addition to a special visual appeal. Overall 7 2/3\". Blade 3 3/7\". Weight approx. 1.8 oz.",
			"Name": "Boker Plus Urban Trapper 3 1/2\" Blade w/G-10 Handle",
			"ItemNumber": "01BO732",
			"RetailPrice": 83.71,
			"ImageUrl": "http://www.motengna.com/core/media/media.nl?id=3191198&c=902676&h=c007f8d766118c333b19",
			"SupplierId": 1,
			"SupplierName": "Moteng",
			"ManufacturerId": 8622,
			"ManufacturerName": "Boker Plus",
			"CategoryId": 13392,
			"CategoryName": "Knives : Folding Blade"
		},
		{
			"Id": 374974,
			"SKU": "4008368",
			"Description": "Tundra Series Freezer Panels have a very unique freezing point of 5 degrees F and are designed to help maintain a consistent freezer temperature in coolers. While not as cold as dry ice, Tundra freezer panels can be used as a suitable replacement. The panels have been shown to maintain days of frozen temperatures in controlled testing. Due to its low freezing point, Tundra freezer panels can take 18-24 hours to freeze. Turn freezer to the lowest setting to ensure freezing. It is recommended that these panels be used to maintain frozen goods. Use weight equivalent to dry ice needed for great reusable results. Store in freezer when not using so they are ready when needed. The ice size is medium.",
			"Name": "Tundra Series 5 Degree High Performance Cooler Pak-Ice Med",
			"ItemNumber": "1203",
			"RetailPrice": 17.82,
			"ImageUrl": "http://www.motengna.com/core/media/media.nl?id=3132313&c=902676&h=76d9215daedefbe5a415",
			"SupplierId": 1,
			"SupplierName": "Moteng",
			"ManufacturerId": 8581,
			"ManufacturerName": "Arctic Ice, LLC",
			"CategoryId": 13262,
			"CategoryName": "Camping : Coolers"
		},
		{
			"Id": 374975,
			"SKU": "4008375",
			"Description": "Chillin' Brew offers the beer drinker, the absolutely best opportunity for the coldest beer possible!  Arctic Ice Chillin' Brew Panel in collegiate color royal blue, in a cooler can keep beer at the perfect drinking temperature longer than ice without the mess or waste. Inside Chillin' Brew panel, the active ingredient changes phases, or freezes at a temperature just above the temperature beer would freeze. This material manipulates the temperature of beer to constantly remain even colder than ice. In fact, Chillin' Brew panel could possibly produce the coldest beer in the entire world! As an added bonus - Chillin' Brew is reusable for a lifetime! To recharge the panels, just pop them in the freezer for 6-10 hours and Chillin' Brew's ready to party! Chillin' Brews active ingredient has been tested for up to 100,000 freeze/thaw cycles without any change in its effectiveness. In addition to being the best way to keep beer at a \"beer cave\" temperature, Chillin' Brew is environmentally friendly. The unique phase change material used in Chillin' Brew is made from animal food stocks and is completely biodegradable and harmless should it ever leak.",
			"Name": "Chillin Brew 28 Degree Collegiate Royal Blue Ice Panel-XL",
			"ItemNumber": "1212",
			"RetailPrice": 27.64,
			"ImageUrl": "http://www.motengna.com/core/media/media.nl?id=3132320&c=902676&h=de10119bd9341058bac7",
			"SupplierId": 1,
			"SupplierName": "Moteng",
			"ManufacturerId": 8581,
			"ManufacturerName": "Arctic Ice, LLC",
			"CategoryId": 13262,
			"CategoryName": "Camping : Coolers"
		},
		{
			"Id": 374976,
			"SKU": "4008378",
			"Description": "Chillin' Brew offers the beer drinker, the absolutely best opportunity for the coldest beer possible!  Arctic Ice Chillin' Brew Panel in collegiate color red, in a cooler can keep beer at the perfect drinking temperature longer than ice without the mess or waste. Inside Chillin' Brew panel, the active ingredient changes phases, or freezes at a temperature just above the temperature beer would freeze. This material manipulates the temperature of beer to constantly remain even colder than ice. In fact, Chillin' Brew panel could possibly produce the coldest beer in the entire world! As an added bonus - Chillin' Brew is reusable for a lifetime! To recharge the panels, just pop them in the freezer for 6-10 hours and Chillin' Brew's ready to party! Chillin' Brews active ingredient has been tested for up to 100,000 freeze/thaw cycles without any change in its effectiveness. In addition to being the best way to keep beer at a \"beer cave\" temperature, Chillin' Brew is environmentally friendly. The unique phase change material used in Chillin' Brew is made from animal food stocks and is completely biodegradable and harmless should it ever leak.",
			"Name": "Chillin Brew 28 Degree Collegiate Red Ice Panel-XL",
			"ItemNumber": "1215",
			"RetailPrice": 27.64,
			"ImageUrl": "http://www.motengna.com/core/media/media.nl?id=3132323&c=902676&h=ad2a1ed470aec30e57a4",
			"SupplierId": 1,
			"SupplierName": "Moteng",
			"ManufacturerId": 8581,
			"ManufacturerName": "Arctic Ice, LLC",
			"CategoryId": 13262,
			"CategoryName": "Camping : Coolers"
		},
		{
			"Id": 374977,
			"SKU": "2006060",
			"Description": "100% Acrylic knit cap. The front features the Kanji characters meaning Master Bladesmith and the words Cold Steel Knives on the back. Available in black or gray.",
			"Name": "Cold Steel Knit Cap 94HCSKBB",
			"ItemNumber": "94HCSKBB",
			"RetailPrice": 12.95,
			"ImageUrl": "http://www.motengna.com/2006060.jpg",
			"SupplierId": 1,
			"SupplierName": "Moteng",
			"ManufacturerId": 8664,
			"ManufacturerName": "Cold Steel",
			"CategoryId": 13384,
			"CategoryName": "Knives : Apparel"
		},
		{
			"Id": 374978,
			"SKU": "4008284",
			"Description": "The mummy style sleeping bag provides plenty of warmth in a realistic pack size. It has highly siliconized synthetic fibers that give it a soft touch and prolong lifespan. Temperature rating is: comfort 32 degrees/low 18 degrees. The Proforce Backpacker Mosquito Net can really make the difference on your next camping trip. Creeping critters can ruin your sleep and in some places-make you quite sick. The Proforce Backpacker Mosquito Net is a fine mesh single point mount mosquito net that is versatile and lightweight. The Backpacker Mosquito Net is perfect for ultra light campers or anyone concerned with critters in the night.",
			"Name": "Snugpak Backpacker Bundle-Mosquito Net & Sleeper Lite Olive",
			"ItemNumber": "BUN105",
			"RetailPrice": 72.11,
			"ImageUrl": "http://www.motengna.com/core/media/media.nl?id=2846887&c=902676&h=978afec2805b0a9ca839",
			"SupplierId": 1,
			"SupplierName": "Moteng",
			"ManufacturerId": 9048,
			"ManufacturerName": "Snugpak",
			"CategoryId": 13256,
			"CategoryName": "Camping : Accessories"
		},
		{
			"Id": 374979,
			"SKU": "4008286",
			"Description": "Olive Snugpak Poncho is over the head smock style coverall. Designed to be worn over personal equipment and backpack. Generously cut to allow use as an emergency bivvi. Has an adjustable hood and thumb loops with Velcro chest map pocket with storm flap. Fully tapped Paratex Dry shell is 100% waterproof and weighs 14 oz. One size fits most. The Jungle Bag is an ideal sleeping bag for tropical conditions. Snugpak has engineered the Jungle Bag with a specific weight of Travelsoft Insulation to maximize the efficiency and the needs of those individuals using it. Travelsoft Insulation was selected and chosen for its exceptional performance in hot and humid conditions. Also with its square foot design and zipper placement the Jungle bag can be opened out into a blanket for more versatility when traveling, or just as a barrier between you and what you are about to lay on. Another great feature of the Jungle Bag is its concealed roll away mosquito netting which can be zipped over the face sealing the Jungle Bag giving you protection against mosquitoes, snakes, etc. Store your sleeping bag, clothing, and any other items you want to keep dry in a Dri Sak. No matter what size you choose or need Snugpak has a size that is sure to be right for your situation. These Dri Sak's are seam taped nylon with a TPU film lamination to ensure protection if your gear takes an unexpected dive into the water. They are a great addition that can be used in conjunction with any of the Snugpak backpacks or any other backpacks. Snugpak Dri Sak bags are not intended to be submerged for extended periods of time. Roll top closure must be closed correctly. It is recommended rolling 3 times and buckle to keep contents dry. Contact with abrasive or sharp objects can damage and/or compromise the integrity and waterproofness.",
			"Name": "Snugpak Jungle Poncho-Jungle Bag-Dri-Sak Bundle - Olive",
			"ItemNumber": "BUN107",
			"RetailPrice": 98.42,
			"ImageUrl": "http://www.motengna.com/core/media/media.nl?id=2846889&c=902676&h=31602640a16b21cb884c",
			"SupplierId": 1,
			"SupplierName": "Moteng",
			"ManufacturerId": 9048,
			"ManufacturerName": "Snugpak",
			"CategoryId": 13256,
			"CategoryName": "Camping : Accessories"
		},
		{
			"Id": 374980,
			"SKU": "4008323",
			"Description": "The Bravo Echo surprises with its 10 cm long blade made from 440A steel, whose size is not necessarily apparent in the folded condition but features a full sized blade when deployed. The stable stainless grip is fabricated in a refined two-tone finish and a slim G10 scale is mounted for increased grippiness. Overall length 9 1/8\" Blade 4\" Thickness 3.4 mm. Weight 7 ozs.",
			"Name": "Magnum Bravo Echo Folding Knife 4\" Blade - 9 1/8\" Overall",
			"ItemNumber": "01EL635",
			"RetailPrice": 36.37,
			"ImageUrl": "http://www.motengna.com/core/media/media.nl?id=3191180&c=902676&h=56468d39df92e6eb7238",
			"SupplierId": 1,
			"SupplierName": "Moteng",
			"ManufacturerId": 8879,
			"ManufacturerName": "Magnum",
			"CategoryId": 13392,
			"CategoryName": "Knives : Folding Blade"
		},
		{
			"Id": 374981,
			"SKU": "4008333",
			"Description": "If there were such a thing as THE perfect day-to-day knife it might look like the Golf Tango. The corrosion-resistant 440A steel blade has a sand-colored coating and therefore provides extra corrosion resistance. The full tang construction gives the knife incredible strength without appearing brutish. The perforations in the grip keep the weight within reason. Green G-10 grip scales. The tang features two lanyard holes. Shipped with green kydex sheath and belt adapter. Overall 7 7/8\"  Blade 4 1/8\"  Thickness 5.3 mm. Weight 7.9 ozs.",
			"Name": "Magnum Golf Tango Fixed Knife 4 1/8\" Blade- 7 7/8\" Overall",
			"ItemNumber": "02SC647",
			"RetailPrice": 55.9,
			"ImageUrl": "http://www.motengna.com/core/media/media.nl?id=3191190&c=902676&h=e902a9377523a7821f58",
			"SupplierId": 1,
			"SupplierName": "Moteng",
			"ManufacturerId": 8879,
			"ManufacturerName": "Magnum",
			"CategoryId": 13391,
			"CategoryName": "Knives : Fixed Blade"
		},
		{
			"Id": 374982,
			"SKU": "4008353",
			"Description": "Mega-Manix has Spydercoâ€™s patented Ball Bearing Lock. Full internal handle liners extend beyond the G-10 handle scales and are scalloped around the perimeter providing exceptional grip and handle control.",
			"Name": "Spyderco Manix2 XL Black G-10 Plainedge Knife",
			"ItemNumber": "C95GP2",
			"RetailPrice": 146.93,
			"ImageUrl": "http://www.motengna.com/4008353_2.jpg",
			"SupplierId": 1,
			"SupplierName": "Moteng",
			"ManufacturerId": 9059,
			"ManufacturerName": "Spyderco",
			"CategoryId": 13392,
			"CategoryName": "Knives : Folding Blade"
		},
		{
			"Id": 374983,
			"SKU": "4008363",
			"Description": "Alaskan Series Cooler Panels freeze at 33.8 F and can efficiently keep food or drinks cold without risk of freezing and is reusable for years. The active ingredients are non-toxic, biodegradable and housed in a rugged container designed to provide maximum surface area to increase the efficiency at which they cool. Store in the freezer until needed and return to the freezer after use. Alaskan series cooler panels will freeze in 6-8 hours in any freezer. The cooler panels can be used in combination with ice to extend ice life up to 50%. Panels are top rack dishwasher safe. The ice size is small.",
			"Name": "Alaskan Series 33 Degree High Performance Cooler Pak-Ice Sm",
			"ItemNumber": "1200",
			"RetailPrice": 14.67,
			"ImageUrl": "http://www.motengna.com/core/media/media.nl?id=3132308&c=902676&h=145fea36f50094337c67",
			"SupplierId": 1,
			"SupplierName": "Moteng",
			"ManufacturerId": 8581,
			"ManufacturerName": "Arctic Ice, LLC",
			"CategoryId": 13262,
			"CategoryName": "Camping : Coolers"
		},
		{
			"Id": 374984,
			"SKU": "4008371",
			"Description": "Chillin Brew Cooler Panels were designed with the beer drinker in mind but are excellent for keeping anything in a cooler, several degrees colder than ice. This Chillin Brews freezing point of 28 degrees makes it uniquely suited for keeping beer or any other beverage at its coldest point possible. This panel is reusable for a lifetime, making it very economical choice for years of colder than ice coolers. Use Chiilin Brew Panels with ice to keep ice frozen up to 50% longer. Store the cooler panels in the freezer for convenience. The panels should freeze in about 6-8 hours. Top rack dishwasher safe. The ice size is small.",
			"Name": "Chillin Brew 28 Degree High Performance Cooler-Ice Size Sm",
			"ItemNumber": "1208",
			"RetailPrice": 15.13,
			"ImageUrl": "http://www.motengna.com/core/media/media.nl?id=3132316&c=902676&h=cef6ce81687ad426b4dd",
			"SupplierId": 1,
			"SupplierName": "Moteng",
			"ManufacturerId": 8581,
			"ManufacturerName": "Arctic Ice, LLC",
			"CategoryId": 13262,
			"CategoryName": "Camping : Coolers"
		},
		{
			"Id": 374985,
			"SKU": "4008275",
			"Description": "Introducing the worldâ€™s first full size lopper sheath with 5-in-1 carrying capacity to hold all your favorite EZ Kut tools! EZ Kut sling pak provides protection for your EZ Kut tools as well as functionality in the field, on the farm, or in your backyard. The innovative pull-thru strap and flex-formed opening makes access to your EZ Kut lopper quick and easy â€” just reach back and grab the big brother lopper and get kuttinâ€™! When you need your EZ Kut ratcheting pruner or folding hand saw just swing the sling pak around and grab â€˜em! Additional pockets are provided for your cell phone or hand held device and EZ Kut carbide sharpener as well. When youâ€™re finished just place it back in the sling and you'll always be ready for action. Guaranteed for life, itâ€™s the perfect complement to your EZ Kut tools!",
			"Name": "EZ KUT Sling Pack",
			"ItemNumber": "3110 SLP",
			"RetailPrice": 81.94,
			"ImageUrl": "http://www.motengna.com/core/media/media.nl?id=2753791&c=902676&h=8a25042ac8636e778548",
			"SupplierId": 1,
			"SupplierName": "Moteng",
			"ManufacturerId": 8728,
			"ManufacturerName": "EZ-Kut Products",
			"CategoryId": 13463,
			"CategoryName": "Tools : Gloves"
		},
		{
			"Id": 374986,
			"SKU": "4008306",
			"Description": "This medium size range bag is perfect for the handgun or long gun shooter. The visual I.D. storage system helps the shooter quickly access shooting glasses, ear plugs, ear muffs, extra magazines, binoculars, shooting targets, tools, ammo dump cups (2), stapler, tape or cleaning supplies. Lift ports are on each end of the bag for easy maneuvering with 2 hands. The bag features padded walls and bottom to protect firearms and ammo while traveling to and from the range. This bag features metal reinforced hardware on the shoulder strap for durability and hands free transportation. Large loop zipper pulls allow for a lock to be added to secure all areas for legal transport.",
			"Name": "G.P.S. Medium Range Bag Tan",
			"ItemNumber": "GPS-1411MRBT",
			"RetailPrice": 78.86,
			"ImageUrl": "http://www.motengna.com/core/media/media.nl?id=2935407&c=902676&h=2def9c87f515cb888d10",
			"SupplierId": 1,
			"SupplierName": "Moteng",
			"ManufacturerId": 8760,
			"ManufacturerName": "G Outdoors",
			"CategoryId": 13444,
			"CategoryName": "Shooting : Accessories"
		},
		{
			"Id": 374987,
			"SKU": "4008307",
			"Description": "The Quad Pistol Case was designed to carry up to  4 pistols in a thick tricot quilted lining. The 2 side pockets are designed to open and lay flat allowing for organized space at the range. In one side pocket is a visual I.D. storage system that helps the shooter quickly identify and access shooting glasses, ear plugs, tools and an ammo dump cup. The other side pocket is designed to store a can of break free, additional magazines and has a triple elastic for a cleaning rod or other accessories. Large loop zipper pulls allow for a lock to be added to secure all areas for legal transport.",
			"Name": "G.P.S. Quad Pistol Case in Tan",
			"ItemNumber": "GPS-1310PCT",
			"RetailPrice": 47.39,
			"ImageUrl": "http://www.motengna.com/core/media/media.nl?id=2935408&c=902676&h=43a0de554bbe3934bf75",
			"SupplierId": 1,
			"SupplierName": "Moteng",
			"ManufacturerId": 8760,
			"ManufacturerName": "G Outdoors",
			"CategoryId": 13444,
			"CategoryName": "Shooting : Accessories"
		},
		{
			"Id": 374988,
			"SKU": "4008347",
			"Description": "Twenty-two (22) multi-drawer design for storing a wide variety of parts and supplies. Clear see-through drawers provide quick identification of each drawers contents. Supports on the cabinet frame provide added strength and improve drawer action. Large, ribbed drawer pulls make it easy to access contents. Built-in stop tabs prevent drawers from pulling out all the way. Easily mounts on wall or stands on bench or counter top. Drawer dividers available to create additional storage. Dimensions: 19\"W x 6\"D x 9\"H.",
			"Name": "Stack-On 22 Drawer Storage Cabinet",
			"ItemNumber": "DS-22",
			"RetailPrice": 22.23,
			"ImageUrl": "http://www.motengna.com/core/media/media.nl?id=3411384&c=902676&h=a7e909e185c399f142b4",
			"SupplierId": 1,
			"SupplierName": "Moteng",
			"ManufacturerId": 9064,
			"ManufacturerName": "Stack-On",
			"CategoryId": 13468,
			"CategoryName": "Tools : Tool Boxes"
		},
		{
			"Id": 374989,
			"SKU": "4008348",
			"Description": "Twenty-seven (27) multi-drawer bin contains 23 medium drawers and 4 large drawers. Contemporary heavy duty cabinet design with wide frame for additional strength and rigidity. Drawer stop tabs prevent spills. Horizontal and vertical supports are made extra strong to increase cabinet strength and improve drawer action. Large, ribbed drawers. 12 5/8'' W x 13 3/8'' H x 6 3/8'' D (32cm x 34cm x 16cm).",
			"Name": "Stack-On 27 Bin Plastic Drawer Cabinet",
			"ItemNumber": "DS-27",
			"RetailPrice": 21.1,
			"ImageUrl": "http://www.motengna.com/core/media/media.nl?id=3411383&c=902676&h=7e9071039183a300dad7",
			"SupplierId": 1,
			"SupplierName": "Moteng",
			"ManufacturerId": 9064,
			"ManufacturerName": "Stack-On",
			"CategoryId": 13468,
			"CategoryName": "Tools : Tool Boxes"
		},
		{
			"Id": 374990,
			"SKU": "4008373",
			"Description": "Chillin Brew Cooler Panels were designed with the beer drinker in mind but are excellent for keeping anything in a cooler, several degrees colder than ice. This Chillin Brews freezing point of 28 degrees makes it uniquely suited for keeping beer or any other beverage at its coldest point possible. This panel is reusable for a lifetime, making it very economical choice for years of colder than ice coolers. Use Chiilin Brew Panels with ice to keep ice frozen up to 50% longer. Store the cooler panels in the freezer for convenience. The panels should freeze in about 6-8 hours. Top rack dishwasher safe. The ice size is large.",
			"Name": "Chillin Brew 28 Degree High Performance Cooler-Ice Size Lrg",
			"ItemNumber": "1210",
			"RetailPrice": 19.92,
			"ImageUrl": "http://www.motengna.com/core/media/media.nl?id=3132318&c=902676&h=463ad5fccb9bb3c7d545",
			"SupplierId": 1,
			"SupplierName": "Moteng",
			"ManufacturerId": 8581,
			"ManufacturerName": "Arctic Ice, LLC",
			"CategoryId": 13262,
			"CategoryName": "Camping : Coolers"
		},
		{
			"Id": 374991,
			"SKU": "4008376",
			"Description": "Chillin' Brew offers the beer drinker, the absolutely best opportunity for the coldest beer possible!  Arctic Ice Chillin' Brew Panel in collegiate color orange, in a cooler can keep beer at the perfect drinking temperature longer than ice without the mess or waste. Inside Chillin' Brew panel, the active ingredient changes phases, or freezes at a temperature just above the temperature beer would freeze. This material manipulates the temperature of beer to constantly remain even colder than ice. In fact, Chillin' Brew panel could possibly produce the coldest beer in the entire world! As an added bonus - Chillin' Brew is reusable for a lifetime! To recharge the panels, just pop them in the freezer for 6-10 hours and Chillin' Brew's ready to party! Chillin' Brews active ingredient has been tested for up to 100,000 freeze/thaw cycles without any change in its effectiveness. In addition to being the best way to keep beer at a \"beer cave\" temperature, Chillin' Brew is environmentally friendly. The unique phase change material used in Chillin' Brew is made from animal food stocks and is completely biodegradable and harmless should it ever leak.",
			"Name": "Chillin Brew 28 Degree Collegiate Orange Ice Panel-XL",
			"ItemNumber": "1213",
			"RetailPrice": 27.64,
			"ImageUrl": "http://www.motengna.com/core/media/media.nl?id=3132321&c=902676&h=75ccb3d794773b4df12a",
			"SupplierId": 1,
			"SupplierName": "Moteng",
			"ManufacturerId": 8581,
			"ManufacturerName": "Arctic Ice, LLC",
			"CategoryId": 13262,
			"CategoryName": "Camping : Coolers"
		}
    ]

    return {brands, categories, prices, products,slideshowImages};
  }
}